// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjrZOyy9c8AlwQaQP8Gm3nRpo3m_rIQJI',
    appId: '1:83779316479:web:91ab5c1405e3839d427aca',
    messagingSenderId: '83779316479',
    projectId: 'shoppingapp-f05b9',
    authDomain: 'shoppingapp-f05b9.firebaseapp.com',
    storageBucket: 'shoppingapp-f05b9.appspot.com',
    measurementId: 'G-GCE532V1JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW5Wr0EuZFAeaDQpc_r-qZrfl8iWE_4lQ',
    appId: '1:83779316479:android:a8a4cb40df44332c427aca',
    messagingSenderId: '83779316479',
    projectId: 'shoppingapp-f05b9',
    storageBucket: 'shoppingapp-f05b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHEdCZVfyAjtjFO2NIQlh9VL-XLBuEVMY',
    appId: '1:83779316479:ios:076f01d5c3d61a72427aca',
    messagingSenderId: '83779316479',
    projectId: 'shoppingapp-f05b9',
    storageBucket: 'shoppingapp-f05b9.appspot.com',
    iosBundleId: 'com.pendragon.us.shoppingpos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHEdCZVfyAjtjFO2NIQlh9VL-XLBuEVMY',
    appId: '1:83779316479:ios:076f01d5c3d61a72427aca',
    messagingSenderId: '83779316479',
    projectId: 'shoppingapp-f05b9',
    storageBucket: 'shoppingapp-f05b9.appspot.com',
    iosBundleId: 'com.pendragon.us.shoppingpos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjrZOyy9c8AlwQaQP8Gm3nRpo3m_rIQJI',
    appId: '1:83779316479:web:9b9ed37739df9baa427aca',
    messagingSenderId: '83779316479',
    projectId: 'shoppingapp-f05b9',
    authDomain: 'shoppingapp-f05b9.firebaseapp.com',
    storageBucket: 'shoppingapp-f05b9.appspot.com',
    measurementId: 'G-E0NFMY9SMD',
  );
}
